### ISSUE TITLE
Separating header files and source code

### ISSUE THREAD

**Issue by Beanie496** [nakst/gf#103]
The generally-agreed convention is for header files to contain function declarations, etc. and source files to contain function definitions, etc.
With that in mind, wouldn't it make sense for `luigi2.h` to be split into `luigi2.h` and `luigi2.cpp`, and `windows.cpp` to be split into `windows.h` and `windows.cpp`, with both following this convention?
Both files are unconditionally included into `gf2.cpp` so there would be no time wasted compiling files that don't need to be. In fact, it would even save time because you could make a change to the source of `windows.cpp` or `luigi2.h` (after splitting them) without having to recompile everything (although I do admit compilation times are just a few seconds anyway).
I'm happy to make this change myself, but I just want to get a sanity check first, in case you don't want this change or I'm missing anything :)

**Comment by nakst** [comment]
In general it is probably better to have headers and source split. But gf is such a small program, it doesn't matter. And in fact, it would be disadvantageous because it would complicate the build script. Not by much, admittedly, but I think the small things matter when it comes to a program that is intended to be easily hackable. Being able to compile gf with a command line as simple as `g++ gf2.cpp -lX11` is very nice in this regard.
